


# Permalinks
permalink:        pretty

# Setup
title:            Virgapes library
tagline:          'Work with chant data in the virgapes alphabet'
description:      'A library for working with chant encoded in the virgapes alphabet'


baseurl: '/virgapes/'


author:
  name:           'Neel Smith'


links:
  - title:  Github repository
    url:  https://github.com/neelsmith/virgapes
    external: true
